---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint -v
  flake8
platforms:
  - name: vpnpeer-setup-instance
    image: ubuntu:xenial
provisioner:
  name: ansible
verifier:
  name: testinfra
