---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: polkadot-validator-validator-node
    image: ubuntu:bionic
    groups:
      - validator
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      polkadot-validator-validator-node:
        polkadot_network_id: ksmcc3
        polkadot_binary_url: 'https://github.com/w3f/polkadot/releases/download/v0.8.22/polkadot'
        polkadot_binary_checksum: 'sha256:7bfe10a0e46385dfb488dcc05ecffbb3075dcbd1d469e44b67a0f5d870185a05'
verifier:
  name: testinfra
  lint:
    name: flake8
