- name: Install 7z  
  apt:
    name: p7zip-full
    state: present
    update_cache: yes

- name: download db
  get_url:
    url: "{{ polkadot_db_snapshot_url }}"
    dest: "/home/polkadot/.local/share/polkadot/chains/{{ polkadot_network_id }}/db.new.7z"
    mode: '0700'
    owner: 'polkadot'
    group: 'polkadot'

- name: stop polkadot service
  systemd:
    name: polkadot.service
    state: stopped

- name: unpack db
  shell: |
    set -o pipefail
    cd /home/polkadot/.local/share/polkadot/chains/{{ polkadot_network_id }}/
    mv db db.back
    7z x db.new.7z
    rm db.new.7z
    chown -R polkadot:polkadot db/
  args:
    executable: /bin/bash

- name: start polkadot service
  systemd:
    name: polkadot.service
    state: started
